const emojiArray = [
  { code: '&#x1F600;', name: 'Grinning Face' },
  { code: '&#x1F602;', name: 'Face with Tears of Joy' },
  { code: '&#x1F923;', name: 'Rolling on the Floor Laughing' },
  { code: '&#x1F60D;', name: 'Smiling Face with Heart-Eyes' },
  { code: '&#x1F618;', name: 'Face Blowing a Kiss' },
  { code: '&#x1F60A;', name: 'Smiling Face with Smiling Eyes' },
  { code: '&#x1F644;', name: 'Face with Rolling Eyes' },
  { code: '&#x1F914;', name: 'Thinking Face' },
  { code: '&#x1F633;', name: 'Flushed Face' },
  { code: '&#x1F62E;', name: 'Face with Open Mouth' },
  { code: '&#x1F62D;', name: 'Loudly Crying Face' },
  { code: '&#x1F605;', name: 'Smiling Face with Open Mouth and Cold Sweat' },
  { code: '&#x1F621;', name: 'Pouting Face' },
  { code: '&#x1F609;', name: 'Winking Face' },
  { code: '&#x1F637;', name: 'Face with Medical Mask' },
  { code: '&#x1F910;', name: 'Zipper-Mouth Face' },
  { code: '&#x1F631;', name: 'Face Screaming in Fear' },
  { code: '&#x1F62A;', name: 'Sleepy Face' },
  { code: '&#x1F613;', name: 'Sad but Relieved Face' },
  { code: '&#x1F60C;', name: 'Relieved Face' },
  { code: '&#x1F60B;', name: 'Winking Face with Tongue' },
  { code: '&#x1F60F;', name: 'Smirking Face' },
  { code: '&#x1F60E;', name: 'Sunglasses' },
  { code: '&#x1F913;', name: 'Nerd Face' },
  { code: '&#x1F624;', name: 'Face with Steam From Nose' },
  { code: '&#x1F914;', name: 'Thinking Face' },
  { code: '&#x1F62C;', name: 'Grimacing Face' },
  { code: '&#x1F910;', name: 'Zipper-Mouth Face' },
  { code: '&#x1F911;', name: 'Money-Mouth Face' },
  { code: '&#x1F912;', name: 'Face with Thermometer' },
  { code: '&#x1F915;', name: 'Face with Head-Bandage' },
  { code: '&#x1F922;', name: 'Face with Symbols on Mouth' },
  { code: '&#x1F927;', name: 'Face with Hand Over Mouth' },
  { code: '&#x1F608;', name: 'Smiling Face with Horns' },
  { code: '&#x1F47F;', name: 'Angry Face with Horns' },
  { code: '&#x1F479;', name: 'Japanese Ogre' },
  { code: '&#x1F47A;', name: 'Japanese Goblin' },
  { code: '&#x1F47B;', name: 'Ghost' },
  { code: '&#x1F47D;', name: 'Alien' },
  { code: '&#x1F47E;', name: 'Alien Monster' },
  { code: '&#x1F916;', name: 'Robot Face' },
  { code: '&#x1F4A9;', name: 'Pile of Poo' },
  { code: '&#x1F63A;', name: 'Smiling Cat with Open Mouth' },
  { code: '&#x1F638;', name: 'Grinning Cat' },
  { code: '&#x1F639;', name: 'Cat with Tears of Joy' },
  { code: '&#x1F63B;', name: 'Smiling Cat with Heart-Eyes' },
  { code: '&#x1F63C;', name: 'Cat with Wry Smile' },
  { code: '&#x1F63D;', name: 'Kissing Cat' },
  { code: '&#x1F640;', name: 'Weary Cat' },
  { code: '&#x1F63F;', name: 'Crying Cat' },
  { code: '&#x1F63E;', name: 'Pouting Cat' },
  { code: '&#x1F648;', name: 'See-No-Evil Monkey' },
  { code: '&#x1F649;', name: 'Hear-No-Evil Monkey' },
  { code: '&#x1F64A;', name: 'Speak-No-Evil Monkey' },
  { code: '&#x1F476;', name: 'Baby' },
  { code: '&#x1F9D2;', name: 'Child' },
  { code: '&#x1F466;', name: 'Boy' },
  { code: '&#x1F467;', name: 'Girl' },
  { code: '&#x1F468;', name: 'Man' },
  { code: '&#x1F469;', name: 'Woman' },
  { code: '&#x1F474;', name: 'Old Man' },
  { code: '&#x1F475;', name: 'Old Woman' },
  { code: '&#x1F64D;', name: 'Person Frowning' },
  { code: '&#x1F64E;', name: 'Person Pouting' },
  { code: '&#x1F645;', name: 'Face with No Good Gesture' },
  { code: '&#x1F646;', name: 'Face with OK Gesture' },
  { code: '&#x1F481;', name: 'Information Desk Person' },
  { code: '&#x1F64B;', name: 'Person Raising Hand' },
  { code: '&#x1F64C;', name: 'Person Bowing' },
  { code: '&#x1F64F;', name: 'Person Tipping Hand' },
  { code: '&#x1F93A;', name: 'Person Gesturing No' },
  { code: '&#x1F93B;', name: 'Person Gesturing OK' },
  { code: '&#x1F926;', name: 'Face Palm' },
  { code: '&#x1F937;', name: 'Shrug' },
  { code: '&#x1F485;', name: 'Person Getting Massage' },
  { code: '&#x1F486;', name: 'Person Getting Haircut' },
  { code: '&#x1F9D6;', name: 'Person Walking' },
]

export { emojiArray }